### ISSUE TITLE
"Not a valid DFS filename" error on Hadoop 2.6.0

### ISSUE THREAD

**Issue by davidallsopp** [JDatta/TarFileSystem#2]
After installing `TarFileSystem` as described in the readme, I try:

`hadoop dfs -ls tar:///user/cloudera/file.tar`

which produces the error:

```
INFO tar.TarFileSystem *** Using Tar file system ***
-ls: Pathname /tar:/user/cloudera/file.tar from /tar:/user/cloudera/file.tar is not a 
    valid DFS filename
```

This is on Hadoop 2.6.0-cdh5.9.0 (Cloudera Distribution of Hadoop).

It looks as if the `tar://` URL is getting incorrectly turned into a pathname?

**Comment by JDatta** [comment]
I haven't tested for this version of Hadoop. Will try to reproduce this.

**Comment by JDatta** [comment]
I could reproduce the issue. I am looking into it.

**Comment by JDatta** [comment]
Oddly, specifying the fully qualified hdfs path of the tar file works. See the following example
``` sh
[hdfs@node1 ~]$ hadoop fs -ls tar:///jd/files.tar
17/01/29 00:19:03 INFO tar.TarFileSystem: *** Using Tar file system ***
-ls: Pathname /tar:/jd/files.tar from /tar:/jd/files.tar is not a valid DFS filename.
Usage: hadoop fs [generic options] -ls [-d] [-h] [-R] [<path> ...]
[hdfs@node1 ~]$ 
[hdfs@node1 ~]$ 
[hdfs@node1 ~]$ hadoop fs -ls tar://hdfs:///jd/files.tar
17/01/29 00:19:08 INFO tar.TarFileSystem: *** Using Tar file system ***
Found 3 items
-rw-rw-r--   2 hdfs hdfs         15 2017-01-27 04:26 tar://hdfs:/jd/files.tar/f1.txt
-rw-rw-r--   2 hdfs hdfs         15 2017-01-27 04:26 tar://hdfs:/jd/files.tar/f2.txt
-rw-rw-r--   2 hdfs hdfs         15 2017-01-27 04:26 tar://hdfs:/jd/files.tar/f3.txt
```

Will look more into it.

**Comment by JDatta** [comment]
Fixed this in and released an interim beta here: https://github.com/JDatta/TarFileSystem/releases/tag/2.0_beta_30_Jan_2017

Please check if this works in your setup.

**Comment by davidallsopp** [comment]
Many thanks for the fast response - that is working in our setup now!
